### ISSUE TITLE
Calc not working on custom function created via Replace

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/Excel-Custom-Functions#108]
Workflow:

1. In Excel PC, I have a UDF implemented via XLL, "=FDS()", throughout an existing workbook.
2. Still in Excel PC, perform a Replace to change all instances of "FDS(" function to "CUSTOMJS.NEWFDS(", which is the name of a custom function that will be implemented by an Office JS add-in.  That add-in is **NOT** currently installed on the PC version of Excel.
3. Save the "translated" workbook.
4. Open the translated workbook in Excel online where the "CUSTOMJS.NEWFDS()" function is available.

The functions do not calculate upon opening the workbook.  Pressing the "Calculate" button on the ribbon or using the Office JS Calculate API will not cause the functions to calculate.

The only way I found to get them to caclulate was to either select the cell, edit the formula and press Enter, or to perform the equivalent via the Office JS API (reassigning the cell.Formula property to itself).

**Comment by keyur32** [comment]
Ah, thank. 

- This is because internally the XLL's save out as "=_xll.FDS()" or "_xll.CUSTOMJS.NEWFDS(".  
- For Javascript Custom Functions, we by default save out with a different prefix "_xldudf". This denotes the feature is saved as a JS custom function, and in current builds, we only look at.

For developers with existing XLLs and COM add-ins, we are working on a 'compatibility' mode, were in your manifest, you'll be able to see 

```
<EquivalentAddins> 
<EquivalentAddin> 
       <ProgID>{progid}</ProgID> 
       <Type>COM</Type> 
  </EquivalentAddin> 
 
  <EquivalentAddin> 
       <FileName>foo.xll</FileName> 
       <Type>XLL</Type> 
  </EquivalentAddin> 
<EquivalentAddins> 

```

Adding this in your manifest will do 2 things:
1. The XLL type denotes, that compatibility between your XLL and Custom Function UDFs: Specifically, it will let your Custom Functions read XLL UDFs, likewise, it will save custom functions out in the XLL format on other platforms like Excel Online or Excel for mac. This will enable these workbooks to be opened on machines with XLL equivalents. 
2. For the COM type:  This will denote the COM add-in portion or UI.

On windows, if your COM add-in is installed or XLL is enabled with the same function names, we will default to that instead of using the web add-in, which we will suppress on load.  If you want to use your web add-in, then we will require the com add-in and XLL be removed off of that machine.

**Comment by keyur32** [comment]
Fixed in 16.0.11505.10000 build. Any build after that will have the capability to save back to older format.

**Comment by fds-ssg** [comment]
I don't see the new behavior in Excel on the PC, Office Insider Version 1904 (Build 11514.20004).  Upon sideloading the add-in (`npm run sideload`) with the EquivalentAddins tags in the manifest, the Office log seems to indicate that tag is not valid:

`3/22/2019 13:36:35	Monitorable	Manifest	Skipped unrecognized XML element for add-in ID : babb1e22-6204-4a76-8e3b-ba686d8481c2, Location : Element Namespace "http://schemas.microsoft.com/office/appforoffice/1.1" : Element Name "EquivalentAddins", Line=30, CharPosition=3`

My manifest included the following (directly beneath the OfficeApp element):
`
	<EquivalentAddins> 
		<EquivalentAddin> 
			<FileName>foo.xll</FileName> 
			<Type>XLL</Type> 
		</EquivalentAddin> 
	</EquivalentAddins> 
`
And after entering a JS custom function, saving the workbook and reopening in an environment without the JS add-in, the function was prefixed with "_xldudf".

**Comment by keyur32** [comment]
Per offline thread, this hasn't fully rolled out. We'll share instructions to get early validation with our launch partners first before enabling it for others.

**Comment by keyur32** [comment]
This is available on Insiders channel! Please help us verify

**Comment by keyur32** [comment]
Closing as this is available on Insiders and will be rolling to prod shortly after custom functions
