### ISSUE TITLE
Issue: Release the dang functions 

### ISSUE THREAD

**Issue by cjtafoya** [OfficeDev/Excel-Custom-Functions#16]
The release schedule for custom JS functions has been dragged out far beyond the initially indicated release date. 

Is there any update on when this will move out of preview? Very frustrating to have a completed commercialized plug-in that can't make it into the Store (we're re-writing it in C# now, huge waste of effort).

**Comment by Rick-Kirkham** [comment]
@cjtafoya I'll see if I can get someone to provide an update on the Preview status.

With respect to the copyright date, it should be the date of the oldest content that is still in the Readme file, so it is correct since that file was published in 2017 and some of the original content is still in it.

**Comment by cjtafoya** [comment]
Thanks Rick, would appreciate any update you might be able to provide.

**Comment by Rick-Kirkham** [comment]
Just heard today that it's going to be in Preview until at least mid-Autumn.
