### ISSUE TITLE
Reported invocation cell doesn't match the actual invocation cell when the function is copied.

### ISSUE THREAD

**Issue by noon-otter** [OfficeDev/Excel-Custom-Functions#199]
My custom array function built in typescript works 99.9% of the time. About 0.1% of the time, the cell that's actually invoked does not match the cell it's referencing. Looking at the `invocation.address` parameter, I've learned that excel is actually invoking a cell other than what it visually says it should be. This only happens when I drag the formula to copy relative formulas. Is this a known issue?

**Comment by ElizabethSamuel-MSFT** [comment]
@noon-otter Sorry to hear that you're hitting an issue.

@RuoyingLiang Can you take a look?

Thanks.

**Comment by noon-otter** [comment]
@ElizabethSamuel-MSFT @RuoyingLiang Any progress? This is a major issue for us as it makes the custom functions less trustworthy.

In the interim, I've solved the issue in my code. The invocation object seems to change values after a few moments. My UDF is using a fetch call, so I send the invocated address along with the fetch request, return it back from the server, and compare the initial invocated address with the current invocated address to see if they've changed. If so, then I re-fetch until the invocated address is stable.

**Comment by RuoyingLiang** [comment]
@noon-otter , thanks for raising the issue. As we cannot repro the issue in our env, could you share more details of repro steps? 
1. Which environment are you using? (Excel desktop, Online or Mac？）It will be great if we can know the build number. 
2. Do you mean when you drag the formula to copy, the copied formula's invocation.address sometimes is not correct? 
3. Currently your workaround is fetch the address later and compare with the initial value you got, right? Could you share your function implements with us so we can do further investigation? Thanks!

**Comment by noon-otter** [comment]
I'm sorry, my company won't let me post code here. This is still an issue for us, but my workaround works for us. I wish I could help more.

**Comment by akrantz** [comment]
@noon-otter I believe the issue may be that you need to capture any info in the invocation object, because after a fetch call, you can no longer rely on the data in the object.

I'm not clear why you are comparing invocation addresses and re-fetching "until the invocated address is stable".

Rather than share your code, you might see if you can clone this repository and make changes to provide a simple example to reproduce the issue. If you can, create a new branch, commit the changes to the branch, and push it to your fork of the repository, then others can use that as the example to investigate the issue.

I would think that the input to the custom function shouldn't depend on the address where it was invoked. If it does, perhaps you could explain why. When you drag the cell, you may be seeing effects of how the various cells are recalculated. Typically the custom function wouldn't want to depend on the recalc behavior. In your scenario, it seems like it does for some reason, and it would be helpful to understand more about why that might be the case. By re-fetching until it is stable, it seems you are probing to know when the recalc has finished. If there is some way to provide more insight into this, it might help better understand what is going on.

**Comment by keyur32** [comment]
Hi allo, marking this issue as closed, per previous response. Please reactivate if further debugging is required. Glad the workaround mentioned above got you unblocked.
