### ISSUE TITLE
Contoso.ADD42 function is not getting appeared in excel.

### ISSUE THREAD

**Issue by ravianand1988** [OfficeDev/Excel-Custom-Functions#2]
Hi, 
I followed steps. hosted Customfunctions.html and customfunctions.js in IIS web app with self SSL certificate. 
 - I hosted only above mentioned files.

 

 - I created a folder in c drive, copied manifest with updated URL
   shared folder and copy network path.
 - I added network path in excel Trusted Add-in catalog and checked show
   in menu. closed excel and open it back.
 - I can see my addin under shared addin.
 - I selected and add in excel too.
 i can see my addin under shared addin. i selected and add in excel too. 

unfortunately i don't see Contoso.ADD42() function. i re did it. still no luck. 
did i miss any step, did i do something wrong. 
looking forward to hear back ASAP.

Thank you.

**Comment by kbrandl** [comment]
@ravianand1988 -- thanks for reaching out about this issue.  Since you've posted this question to Stack Overflow (and are getting assistance there), I'm going to close this Issue here in GitHub, to avoid tracking it in both places. 

(For reference, the corresponding Stack Overflow post is here: https://stackoverflow.com/questions/47211087/contoso-add42-function-is-not-appearing-in-excel).
