### ISSUE TITLE
Documentation needs to be clearer when sharing runtime between task pane and custom functions

### ISSUE THREAD

**Issue by paulfrench** [OfficeDev/Excel-Custom-Functions#214]
I'm running a taskpane and custom functions under a shared runtime in Excel on the web.

I've been banging my head against a wall following...

https://docs.microsoft.com/en-gb/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial

I've been trying to get my custom functions to work when using a shared runtime. Eventually by tracking down some samples namely...

https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-global-state

I finally found the missing link. For some reason within the taskpane.[ts|js] file you need to associate your custom functions with a name. I'm not sure if the name is relevant but I had to add to the taskpane.[ts|js]...
```
Office.initialize = () => {
  CustomFunctions.associate('MYFUNC1', myFunc1)
  CustomFunctions.associate('MYFUNC2', myFunc2)
etc
}
```
...then things started to work. I cannot see anywhere in the documentation explaining this? Maybe I misunderstand something and if I do could you please explain what I have done wrong?

Cheers

**Comment by lindalu-MSFT** [comment]
@keyur32 @mscharlock We need a SME to verify this update to the docs.

**Comment by mscharlock** [comment]
@RuoyingLiang can you have a quick look at this as well? Thanks!

**Comment by weshi** [comment]
If you include your functions.js in your taskpane.html, you should not need to steps you listed above.

**Comment by paulfrench** [comment]
I'm using typescript generated by yeoman. Webpack is used to include functions.ts. If you start here and then convert to using the shared runtime I don't think it mentions anything about making sure functions.js is included in taskpane.html ?

**Comment by akrantz** [comment]
The Yo Office template is designed for the separate runtimes between custom functions and the task pane. It doesn't reflect the changes needed when a single shared runtime is used for the task pane as well as the custom function.

@keyur32 @TCourtneyOwen @lindalu-MSFT We need to coordinate about what changes are needed for the shared runtime. At a minimum it would help to have documentation to explain what changes to make to the template. 

@paulfrench Currently the webpack config will create separate bundles for the custom functions and the task pane. You should be able to modify this so the functions.ts/js file is part of the taskpane bundle instead of separate. In the manifest, you can change it so that the custom functions script comes from taskpane.html/js instead of functions.html.js. The webpack config has a plugin which automatically generates the custom function metadata and emits the CustomFunctions.associate() calls so the developer doesn't miss it. You might need to adjust the webpack config settings for the plugin so it is in the correct bundle.

**Comment by paulfrench** [comment]
Okay thanks, I'll give it a go. What I have works fine but I still need to associate each custom function myself. I'll see if I can remove this step. Thanks

**Comment by mscharlock** [comment]
@TCourtneyOwen @akrantz  @lindalu-MSFT I'll put the doc changes on my backlog! :)
