### ISSUE TITLE
Add custom functions to existing visual studio generated add-in

### ISSUE THREAD

**Issue by chucklay** [OfficeDev/Excel-Custom-Functions#215]
Hello. This is primarily a documentation issue.

I have a task pane add-in that was generated using the VS Office/Sharepoint workload that I'm trying to add custom functions to. However, I can't get it to work, and all the documentation on custom functions I can find essentially boils down to generating this template and working from there.

What exactly would I need to add to my manifest to point to a js/html file and have it generate usable functions? I've tried setting `JS-URL`, `JSON-URL`, and `HTML-URL` in my resources/urls, as well as setting script/page/metadata entries under an `<ExtensionPoint xsi:type="CustomFunctions">` entry.

However, it's not generating the JSON metadata file, and I don't have access to my functions.

I'm sure that I'm missing something in my manifest, but there's no documentation that gives me any hint as to what it could be. Any help would be greatly appreciated.

**Comment by chucklay** [comment]
I've stuck the relevant portions of my manifest in this SO question: https://stackoverflow.com/questions/62349701/adding-custom-functions-to-existing-excel-add-in-generated-by-visual-studio

I've also added this:
```
  <Requirements>
      <Sets DefaultMinVersion="1.1">
          <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
      </Sets>
  </Requirements>
```

Still not having any luck.

**Comment by akrantz** [comment]
This is difficult to document as there are various changes. I suggest using Yo Office to create a new project for Excel Custom Functions and then comparing the differences against your project.

Primarily you'll see differences with the webpack config which allows for generation of the json, and the manifest changes for the custom function additions. 

Debugging for custom functions is different than taskpane since it runs in a separate runtime. This is designed for debugging using VS Code for the custom functions instead of using Visual Studio or browser devtools for the webview where the taskpane runs.

**Comment by keyur32** [comment]
Adam is correct. I did respond to the stack overflow topic as it may be relavent. The recommendation for VS and getting debugging would be to configure your add-in to use shared runtime. Closing this instance.
