### ISSUE TITLE
Creating a new `Excel.RequestContext` class in my custom function makes it return `#VALUE`

### ISSUE THREAD

**Issue by JoshG1987** [OfficeDev/Excel-Custom-Functions#227]
Operating System: Windows 10
Node Version: 10.16.0
Office: Excel in the web (Office 365)

If I try to use the Excel API in my custom function, it always returns `#VALUE` when I call it. The simplest possible reproducible example is as follows:

1. Follow [this](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows) tutorial and use Yeoman to generate a new "Excel Custom Functions Add-in project" using Javascript.
2. Remove all existing functions in `./src/functions/functions.js`
3. Follow [this](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function) tutorial and copy the sample code into the directory from step 2 verbatim (I also tried changing the `var` declarations to `let` in case this was some kind of scoping issue)
4. Run `npm run build` and `npm run start:web` and add my manifest to my Excel workbook on the web

Calling the custom function created above in Excel returns `#VALUE`. However, if I create a custom function which doesn't ever create a new `Excel.RequestContext` object, it behaves as expected. Is the documentation incorrect and referencing the API from within a custom function is not supported? If not, what else could be wrong here?

Note: I've also tried [using a shared runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial)

**Comment by lindalu-MSFT** [comment]
Hi, sorry for the delayed response! We're a bit short on resources this week due to vacations. I assigned this to the correct team to investigate. Thanks, linda

**Comment by Xiirf** [comment]
Hello,
I have the same problem, I tried the same actions but I can't access the API from my custom functions. For my part, the error is that 'Excel' is not defined (log).
I don't know if the functionality is available despite this link https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function.

**Comment by ElizabethSamuel-MSFT** [comment]
@RuoyingLiang Any update on this? Thx.

**Comment by ivanosipov95** [comment]
Also, have the same issue. Any updates?

**Comment by ElizabethSamuel-MSFT** [comment]
@grangeryy Is this something you can help with or direct? Thx.

**Comment by ivanosipov95** [comment]
@grangeryy, @ElizabethSamuel-MSFT Hi, any updates?

**Comment by itoxable** [comment]
Hi There, I'm have the same issue. Any updates?

**Comment by grangeryy** [comment]
@JoshG1987 does this issue still repro? If yes, could you share the test project link to us so we can investigate faster?
@Xiirf @ivanosipov95  to call JS APIs in Custom Functions, you need to configure your add-in to use [shared runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows) first.

**Comment by YakeHoFoong** [comment]
I am seeing the same issue. Could you please re-open this issue and look into it? Thank you.

**Comment by AlexJerabek** [comment]
Sorry to hear that @YakeHoFoong. @ZYUN-MSFT, could you please investigate?

**Comment by MiaofeiWang** [comment]
Hi @YakeHoFoong , sorry to hear that. For this sample, the parameter needs to be a string quoted by `"` or `'`, like `=CONTOSO.getRangeValue("A1")`. If the result is `#VALUE`, it may be because the parameter you are passing in is a cell range which is **not** quoted, like `getRangeValue(A1)`.  Could you please help check it and let us know if not resolved?

**Comment by YakeHoFoong** [comment]
Hi @MiaofeiWang , I was not specifically using the exact same example. For testing, I used Script Lab, copied and modified the sphereVolume example, and when I just added one line "const context = new Excel.RequestContext();" in the function before the return statement, and the return value became "#VALUE". I tried changing the function to async and added one more line "await context.sync();", but still getting "#VALUE". If I now remove the line "const context = new Excel.RequestContext();", the function properly returns a number again.

**Comment by MiaofeiWang** [comment]
@YakeHoFoong , as said [in the document](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function), "To call Excel JavaScript APIs from your custom function, you'll need to use a [shared runtime](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes#shared-runtime)". While, unluckily, Script Lab is not configured to use the SharedRuntime feature. `const context = new Excel.RequestContext()` is a kind of calling Excel JS API and that's why the function failed with "#VALUE" result.

Would you please try some add-in using SharedRuntime? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime

**Comment by YakeHoFoong** [comment]
@MiaofeiWang thank you for your explanation. I have tested with a test add-in using Shared Runtime, and it works. Please close this issue. Thanks again for your help.
