### ISSUE TITLE
VSCode Breakpoints not working

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/Excel-Custom-Functions#236]
I am trying to use VSCode to debug Excel JS Custom functions on Windows, using Yo Office, the Custom Funcs Tutorial, and UI-less custom functions debugging instructions. I have not modified the manifest or any code. I am not using the shared runtime. Everything works except the debug does not stop at breakpoints:

    the breakpoints show as unbound after Excel starts
    Debug console shows "Could not load source map from foundation.win32.bundle.map"

Suggestions please. I am using Excel Insider fast build 13430.20000 64-bit and VSCode 1.51.0

**Comment by akrantz** [comment]
The "foundation.win32.bundle" is the JavaScript bundle for Office code which doesn't include your code. You don't need the source map for it since you're not going to debug into that code.

The add-in files are downloaded into the "wef cache". I think there might be an issue where the source map files are downloaded with the wrong name.

In a command prompt:
Go to the wef cache root folder: C:\Users\USERNAME\AppData\Local\Microsoft\Office\16.0\Wef
Go to this folder: CustomFunctions\v1.7\Registry
Go in two more subdirs. The names will look similar to:  \4RQzQEXZWJX43kK6IZbSSA==\ca968be6-728b-4f14-ba3c-3e614effa9bd
`type javascript.js.link` to view the contents of the file. It will be another path. Then go to that directory.
The custom functions javascript bundle is named "bundle.js".
The source map should be named "functions.js.map".  This should also be the name shown for the last line in "bundle.js" for the sourceMappingUrl comment.

Let me know if you instead have a map file named "bundle.js.map".

**Comment by FastExcel** [comment]
Thanks Adam

Sadly it all looks correct.

The only entry for js.map in bundle.js is indeed the last line sourceMappingUrl and it says functions.js.map
And the other file in that subdir is called functions.js.map

Charles

**Comment by TCourtneyOwen** [comment]
@FastExcel I am also reproing this behavior and am investigating.

-Courtney

**Comment by igor-ribeiiro** [comment]
@FastExcel A PR has just be made for fixing this issue: https://github.com/OfficeDev/Excel-Custom-Functions/pull/263
It will soon be merged and your issue fixed should be available soon.

Thanks for the investigation and comments,
Igor Ribeiro

**Comment by akrantz** [comment]
Let's not close this until the fix is available.
