### ISSUE TITLE
A custom function became BUSY if it accepted TODAY as a parameter and break Excel

### ISSUE THREAD

**Issue by leybal** [OfficeDev/Excel-Custom-Functions#262]
# Prerequisites
Hi.
Our team develop add-in for Excel. We notice custom function performance issue. If a custom formula accept the formula TODAY as a parameter, then this formula is recalculated on any change to the data on a sheet. 500 of these formulas lead to a critical error Excel and page reload. Please take a llok at [the video](https://drive.google.com/file/d/1rx59gZ9r-HONbwF9JxUxQ-OFPdwQDID_/view?usp=sharing).
At the same time, the standard formula SUM is not recalculated on any change to the data on a sheet.
Is it possible not to recalculate custom functions in such cases? Are you planning to optimize custom functions similar to how the standard SUMA formula works now?

# Expected behavior
Editing a third-party cell does not recalculate custom function, so that we can add more than 500 formulas with TODAY 
as a parameter.

# Current behavior
500 custom functions with TODAY as a parameter break Excel and lead to the page reload.

## Steps to Reproduce
1. add =TODAY() to cell A1
2. add 500 formulas =SCRIPTLAB.BASICCUSTOMFUNCTION.SPHEREVOLUME($A$1)
3. edit any empty cell.

## Context
* Operating System: Windows 10
* Office version: 16.0.13921.31876
* Browser: Chrome  89.0.4389.90
* Session ID: 1ce4b4cb-3885-4c77-989a-a20b43ad3cf9

**Comment by grangeryy** [comment]
Hey @leybal we also notice this issue and here the bug we are using to track: 4633260

**Comment by leybal** [comment]
Thanks for answer. How we can track the progress of this bug?

**Comment by grangeryy** [comment]
We're still in the investigation into this and will update more information once we get progress. Thx!

**Comment by grangeryy** [comment]
Hey @leybal, there seems to be several asks/issues in this item.
1. Today() triggers recalculate while SUM doesn't.  - This is by design for Excel calculation logic after surfing the code. I guess the reason behind is for Today or rand(), there's correlation in the formulas so it needs to update(recalculate) to make the data is up-to-date.
2. Custom function performance issue. - From our test, the calculation time for CFs is ~500-800ms. And the video seems the same. Is 500-800ms still feel slow to you?
3. Critical error. - We're checking the log based on the SessionID you provided, but unfortunately we haven't find any Custom Functions error related so far. We'll continue the investigation on the log. Can you still repro the error since we tried several times but didn't hit the same issue?

**Comment by leybal** [comment]
Hey @grangeryy. It looks like a misunderstanding has occurred. Let me help with a clarification.

2.  Performance issue is not related to the calculation time. We have 2 formulas that refer to `TODAY()`: the standard `SUM()` formula and a custom function, e.g. `SCRIPTLAB.BASICCUSTOMFUNCTION.SPHEREVOLUME()`. By the performance issue, I meant that CFs are recalculated whereas the SUM() is not recalculated when a user edits an empty cell. 

3. You probably haven't find the CFs error in the logs, because the tab with the Excel online does not respond after a lot of updates and the tab reloading. The problem is not in custom formulas but in a large number of requests to Microsoft servers.

We have recorded a [new video](https://drive.google.com/file/d/1cjSyer32u1L4bDU-xD5K5a372BGUFUXj/view?usp=sharing).
Session ID d57c920d-bde3-4e45-a07e-03a645a32b1f
Today we noticed that Excel online can handle even 3,000 custom formulas that refer to `TODAY()`. The error occurs when there are more than 4000 CFs. We receive the following error: "We're not able to contact the server. It might not be responding, or your Internet connection may have been interrupted. Please try again".

Our add-in for Excel contains templates in which from 5 to 20 thousand CFs that link that refer to `TODAY()`. A user can download a template and see the CFs results, but cannot edit or work with the template, because an error will fall. A CFs in Excel for Windows temporarily show #CALC if they cannot work correctly. In online, this causes the page to reload.
Is there a chance that the custom functions will work the same as the standard formula `SUM()` and won't recalculate when a user edits an empty cell?

**Comment by grangeryy** [comment]
@leybal Sorry for the late response but this is more complicated than original thought. 

Updating:
There are 4000 ~5000 custom functions in the workbook, the repro is triggering lots of whole calculation at a very short time. (There are lots of CF calculations run at the same time) which leads to a perf improvement ask. We've figuring out the root cause and track using backlog:4991412. I'll update once we have progress. Thx!

**Comment by grangeryy** [comment]
@leybal, this issue turns into a general perf issue since there are 4000 ~5000 custom functions in the workbook and they actually trigger lots of whole calculation within a very short time, leading to lots of CF calculations at the same time. This will be a long term performance improvement feature instead of simple bug fixing. I'll change the issue title and pls let me know whether will be a blocker for your customers. THX!
