### ISSUE TITLE
Question: Support for code generation

### ISSUE THREAD

**Issue by HughGrovesArup** [OfficeDev/Excel-Custom-Functions#296]
Currently, we have an ExcelDNA based Excel desktop plugin. This plugin dynamically generates a large number of functions (UDFs) to make interacting with a company internal API simple.

We would like to move to the new javascript API to allow our plugin to work across all versions of Excel, however it does not seem like the javascript API allows for this kind of behaviour. Is this feature ever likely to end up on the roadmap?

The alternative approach we could have is to do code generation e.g. every evening to generate a static plugin and deploy it for use. However, we have found publishing javascript based plugins to our users very problematic, are there any links to best practice that would allow us to do these kinds of daily deployments?

**Comment by millerds** [comment]
I can't say that I'm familiar with ExcelDNA, but from what I gather it's a 3rd party library that allows you to use .Net to generate code supported natively by Excel.

What is it about the JavaScript API that you believe is missing that would support your dynamic scenario?  What is it about deploying JavaScript based plugins that you are finding problematic?

**Comment by HughGrovesArup** [comment]
We have an API that allows users to perform engineering calculations. The calculations are grouped into libraries, and some of these libraries update almost daily.

The actual API we call is static, but is not very friendly for non-programmers (takes in JSON and IDs). To make it accessible to our staff we create UDFs that are easy for them to use, in the background we package up their inputs, fire them off to the API, receive results, and then pass them back to the user.

With our current setup the user chooses which version of a given library they want to interact with, and then at Excel start the UDFs are dynamically generated based on our API. The advantage of this approach is that we can deploy one version of our Excel plugin, but the user will constantly be able to access the latest calculations provided by our API. Because its just a normal Excel plugin we are able to write an installer that the user can download and install without admin rights (self-serve).

I believe that this approach is not possible with the javascript API because I do not see any mechanism whereby I could dynamically generate and register the UDFs when the user loads the plugin? I would be interested to know if I am wrong!

The deployment problem is probably just a consequence of being within a large corporation and needing to find the person with the rights to upload and deploy our manifest. Our frequency of updates (daily) will make this harder. I have also not seen a mechanism for users to trial beta versions of plugins apart from sideloading (which we have found to be hard to explain to non-technical users).

**Comment by millerds** [comment]
Given you asked this question in this repo, which is the sample template for a custom functions add-in, I'm assuming that is what you are looking at.  You can find documentation on custom fucctions at https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview.  Your libraries of functions would be js files served from the service you have to deliver the add-in content.  Seems like you could design a core add-in that allows for the selection of the set of functions and then deliver the functions that match the selection or maybe you have a standard function signature that makes a service call with a version argument and your service uses that to pick the right code to run and return the result.

There are probably some details about building this that I'm unaware of (haven't tried building it myself).  The paradigm is a bit different since you aren't delivering an installer with everything built in, but rather a manifest that tells the client where to go on the web to get the functionality you want to provide.

**Comment by HughGrovesArup** [comment]
Interesting, I think I need to better understand how these new add-ins are strung together. The functionality that you describe of being able to select functions, and then make the relevant UDFs available to the plugin user would suit my needs.

You wouldn't happen to know of any project that has tried this before so I could see how it has been done?

**Comment by HughGrovesArup** [comment]
Also I apologise if I am asking these questions on the wrong repository.

**Comment by millerds** [comment]
Unfortunately I don't know of a project that is doing something like this . . . I'm just trying to incorporate you're description into what I know of this this newer model,

Documentation can be found at  https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins including some comments about the difference between it and previous plugin models.

**Comment by parched** [comment]
We have the very similar use case as @HughGrovesArup. We have library of engineering functions that are exposed by a self describing web API. We want to write an add-in that allows these to be called in Excel as a custom functions. Ideally the add-in would query our API for the list of function when it starts up and registers wrappers for them with Excel. Otherwise, we're going to have to release a new version of the add-in every time a function is added to our API (Although, releasing a new web add-in each time will be easier than an XLL, I assume).

I'm considering creating an XLL using ExcelDna which allows dynamically registering custom functions (internally it calls [`xlfRegister` from the XLL SDK](https://docs.microsoft.com/en-us/office/client-developer/excel/xlfregister-form-1)). I'd prefer to use a web add-in though. It appears possible to dynamically register functions with a web add-in like [this](https://github.com/OfficeDev/script-lab/blob/b2f54fda3868330551aaa076de1e592cff88e751/packages/editor/src/pages/CustomFunctions/components/App/utilities/index.ts#L44), but that API is undocumented as far as I can tell.

**Comment by AlexJerabek** [comment]
Since the dynamic association of custom functions isn't supported, I'm going to close this issue. If you haven't already, please submit a [feature request](https://learn.microsoft.com/en-us/office/dev/add-ins/resources/resources-links-help#feature-request-and-general-help).
