### ISSUE TITLE
Runtime is not shared between taskpane and custom functions in Excel on the web

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/Excel-Custom-Functions#304]
# Expected behavior

Runtime and data are shared between taskpane and custom functions in Excel on the web

# Current behavior

I followed this guide to share runtime and cookie between taskpane and custom function. I tested in offline Excel (in both Mac and Window) and it works fine. However, when I sideload the function on the web, the taskpane is loaded as an iframe inside the web, thus the taskpane and custom functions have different runtime and cookie. There is no error message, they just don't share the run time any more, which messes up my custom function which uses cookie entered by user from the taskpane to validate them.

## Context

Latest Excel on the web

## Failure Logs

There is no error message. My target audience is not people using Excel on the web but it is a part of the verification process to publish the add-in to Appsource so I need to find a way to make it works on the web as well

**Comment by rundongmsft** [comment]
Hi @tqdo , I've replied in [Stack Overflow](https://stackoverflow.com/questions/70841486/cookie-is-not-shared-between-taskpane-and-custom-functions-in-excel-on-the-web). Hopes it can help you.

**Comment by sachin161194** [comment]
Hi @tqdo @rundongmsft  , I am also having similar issue.
In my case,
 With shared runtime based implementation: Taskpane is not working properly in Desktop as well as in web.
whenever I am running my add-in , first time its working fine ,custom functions as well as taskpane both are working fine.
but in case I closed my addin and open it again then its getting opened on the same inner route where I closed it earlier (instead of landing page) and skips the authentication as well.

previously whenever i closed it and open it again ,it was always opening landing page with initial state.

I think it happening because of this lifetime=long parameter :-
<Runtime resid="Taskpane.Url" **lifetime="long"** />

Please suggest how to resolve it ,is there any way to capture taskpane open and closed events , 
I tried consoling from source location of taskpane.html but its not getting logged from 2nd reopening onwards of taskpane.

I am only getting this in console whenever I am opening and closing taskpane :- 

![image](https://user-images.githubusercontent.com/92863921/151743930-85a22aef-c205-413c-9f5d-8654e36ffaba.png)

**Comment by rundongmsft** [comment]
Hi @sachin161194 , in shared runtime, `the lifetime needs to be long so that your add-in code can run even when the task pane is closed`. In other words, closing taskpane with shared runtime means hidden it.

In your case of desktop, `after close add-in and reopen it, the same inner route will appear and the authentication will skip as well` is the **right behavior**. The reason why **taskpane is not working properly in web** is that the cookie was blocked by a security feature of web browser. You can refer to my previous answer to keep web consistent with desktop.

If you want to let taskpane with shared runtime always opened with initial state, you can capture `onVisibilityModeChanged` event. For example:
``` javascript
Office.initialize = () => {
  Office.addin.onVisibilityModeChanged(function (args) {
    if ((args.visibilityMode == "Hidden"))
    {
      document.cookie = "" // clear the cookie
    }
  })
}
```

Thanks,
Rundong
