### ISSUE TITLE
Manifest generated by yo office for the Custom Functions template has issues with the Functions URLs

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/Excel-Custom-Functions#310]
The generated manifest for the Custom Functions project template has the following entries for the Functions URLs:

      <bt:Urls>
        <bt:Url id="Functions.Script.Url" DefaultValue="https://localhost:3000/dist/functions.js"/>
        <bt:Url id="Functions.Metadata.Url" DefaultValue="https://localhost:3000/dist/functions.json"/>
        <bt:Url id="Functions.Page.Url" DefaultValue="https://localhost:3000/dist/functions.html"/>
...
      </bt:Urls>

They all reference a file in the dist folder. This works great when the project is debugged from localhost, but when the project is deployed to a web server the reference to /dist/ is still in the url in the manifest and these files won't load when there isn't a dist folder on the deployed web server.

I believe the /dist part of the URLs can be removed, but this obviously needs to be checked with the Custom Functions FC.

**Comment by millerds** [comment]
It is my understanding that that any reference to localhost in the manifest will need to be updated once you have the add-in code deployed to somewhere else.  If that somewhere else deployment doesn't include the '/dist' in the path, then that can be changed.  We don't provide a manifest with urls pointing to other deployed locations as we don't know what those locations would be.

**Comment by jakobpn** [comment]
The build process is generating a production manifest and in that manifest localhost is replaced with the production server.

**Comment by akrantz** [comment]
This is by design. The /dist folder being used is a workaround since webpack-dev-server from the root will serve up things from memory designed for a browser context, but the custom functions runtime is not a browser context. The alternate path is because these are built to disk, and that disk location is served up, which works around the issue. It's not intended as how it would be served up for a production manifest.

**Comment by akrantz** [comment]
The webpack config rule that does the localhost replacement can be modified to include removing the /dist as well for production.

**Comment by millerds** [comment]
Thanks Adam.  I was just about to confirm this myself.

**Comment by millerds** [comment]
@jakobpn can you confirm that you need the URLs to have the dist part of the URL removed?  Is something broken with the dist part of the URL and does removing it fix some bad behavior you are seeing?

**Comment by jakobpn** [comment]
Thank you @akrantz and @millerds! It sounds to me like /dist is needed in the development manifest. I can confirm that it is not needed in the production manifest. In fact, the add-in won't load the custom functions, if it is there. Seems like this need to be fixed in the webpack config that yo office is generating.

**Comment by svickers** [comment]
I had to remove the `/dist/` from my manfiest.xml file even when running locally with `npm run dev-server`.  functions.js and functions.json are being served from the root, not sure what is up with that.  I've tried multiple fresh projects with the typescript generator and out of the box the functions don't work at all because of the dist folder.

**Comment by millerds** [comment]
Note: Recently an update was published to the templates (ts and js) that changes the /dist/ to /public/ in order to accommodate a performance improvement to loading the functions.

The reason for the use of the compiled subfolder is because webpack dev server will emit the file with extra code (designed for import statement compatibility for different es version) in the functions.js and excel CF can't handle the extra code.  If you run the dev server (npm run dev-server) you can browse to both https://localhost:3000/functions.js and https://localhost:3000/public/functions.js and see the difference in the file.  There doesn't seem to be a way to omit this extra code.  Since production isn't serving up files using webpack dev server this part is unnecessary.

I'm putting together a PR to have the build for production remove the subdirectory for the functions file from the manifest.

**Comment by millerds** [comment]
template should be updated now.
