### ISSUE TITLE
Custom functions with TODAY() autorefresh when unrelated cells change

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/Excel-Custom-Functions#369]
*** NOTE: If you have an issue running your custom function, please log an issue in the official office-js repo here: [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues) ***

I have a custom function which takes a date as an input. I can also use TODAY() as an input like this: MY_CUSTOM_FUNCTION(TODAY()) and everything works fine.

Let say in my spreadsheet I have 2 cells which have values
A1: =MY_CUSTOM_FUNCTION(TODAY())
A2: 3

Whenever I change the value of cell A2 (to 2, 4, or basically any value), cell A1 is refreshed. I am not sure why since cells A1 and A2 have nothing to do with each other. Is there any way to stop this autorefresh behavior? Appreciate any help.

**Comment by AlexJerabek** [comment]
Hi @tqdo,

The `TODAY()` function is [volatile](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-volatile). That means it recalculates when Excel recalculates. The [Application](https://learn.microsoft.com/en-us/javascript/api/excel/excel.application?view=excel-js-preview) object offers properties and methods to control when Excel recalculates.

Since this isn't an issue with the template, I'm going to close this issue. I'd recommend asking questions like this on [Stack Overflow (with the office-js tag)](https://stackoverflow.com/questions/tagged/office-js). There, members of the community can provide answers more quickly.
