### ISSUE TITLE
Custom functions not showing up

### ISSUE THREAD

**Issue by atestu** [OfficeDev/Excel-Custom-Functions#72]
Here's my excel version, on Windows:

<img width="376" alt="screenshot 2018-12-15 15 48 58" src="https://user-images.githubusercontent.com/22851/50047345-2a2ec480-0081-11e9-8197-4bab7bc98934.png">

I ran `npm start` and it does load the add-in but not the custom functions part. I see the pane but that's it. I must have reinstalled office 5 times today... I used the office deploy tool and changed the xml file to make sure I was on InsiderFast, but it's still not working. What am I doing wrong? 

I appreciate your help, I'm excited to write my first add-in!

**Comment by keyur32** [comment]
Hey, sorry for the issue and thanks for reporting.  We confirmed, the december update has an install a bug on the 32 bit version of windows. We're working to get it fixed as soon as possible.  To workaround, you can install the 64 bit version of the Office build.  Additionally, you can build your add-in using Excel Online until we get it fixed.  Apologies for the inconvenience.

**Comment by keyur32** [comment]
Here is also a workaround for you on the 32 bit version you can follow: 
1. Download the file to: https://github.com/OfficeDev/Excel-Custom-Functions/blob/december-insiders-workaround/excel-udf-host.win32.bundle 
2. Copy it your "C:\Program Files (x86)\Microsoft Office\root\Office16" folder.

This bug should be fixed in the next insiders build update in min January. thanks again

**Comment by atestu** [comment]
I actually have the 64 bit version installed, which I just reinstalled just in case... I also put that file in the folder in question (had to create root/Office16 though) and it still isn't working.

My Windows version is Version 10.0.17134 Build 17134
Using a brand new Surface laptop 2

**Comment by atestu** [comment]
I tried uploading the manifest.xml file in Excel online and nothing happens at all. The sidebar doesn't open and when I go back to the add-in menu it's like I did nothing

**Comment by keyur32** [comment]
Thanks. Odd, Ok, 

On Excel Online:  Do you get any errors written to your browser console?

On windows can you try the following: 
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-best-practices#troubleshooting  

and let me know what errors you get. Likewise, if you go to File > Send Feedback > Send a frown, we will also be able to collect some logs.  We'll hopefully have debugging guidance in VS code available next month as well as fixing the 32 bit version.

**Comment by atestu** [comment]
Yes the error is the CORS error and I don't know how to fix it tbh.
HOWEVER, I cloned the preview-sept-2018-javascript branch of this repo and it works in Excel desktop! 👍

**Comment by atestu** [comment]
I tried in Edge and Firefox

**Comment by akrantz** [comment]
The CORS issue has been fixed with https://github.com/OfficeDev/Excel-Custom-Functions/pull/73.

Also, just so you are aware, we have reverted Yo Office back to use the Sept 2018 preview version. That is the "yo-office" branch of this repository. The master branch still has the latest changes which you can try out and provide feedback on.
